### PR TITLE
add device id for Samsung 960 series

### PR DESCRIPTION
**Pull request by koush**

### CODE REVIEW

**Comment by RehabMan** [comment]
Pulled... but...

Keep in mind the patched kext matches on class, not device-id.  The code you added is only used if you set use_class_match=0.

**Comment by koush** [comment]
Yep. I'm actually using the spoofed class id via SSDT-NVMe-Pcc.aml anyways. Just noticed the device ID for my drive was missing when reading the script and added it for documentation purposes.

**Comment by RehabMan** [comment]
OK.

**Comment by koush** [comment]
This may be of some interest to you for your README.

In:
https://github.com/koush/EFI-X99/tree/master/CLOVER/bin

generate-spoof-nvme(.py/.sh) - Find all NVMe devices, create a spoofed SSDT.aml for them.

**Comment by RehabMan** [comment]
It is ok, but works only in a subset of the possible scenarios.
And it only helps if you already have OSX/macOS installed.

It will not work if there is no ACPI identity for the NVMe drive (see my guide on tmx for more info).
And it doesn't help you use the class-code spoof prior to installing (manual creating of the SSDT based on info from Windows Device Manager is the way there)

**Pull request merged**
