### PR TITLE
add patch for SSD on 10.15.1

### PR DESCRIPTION
**Pull request by jief666**

### CODE REVIEW

**Comment by jamesst20** [comment]
Hi @jief666 

Do you have a patch ready for 11.2.2 (Big Sur) for an Hynix﻿ NVME SSD

**Comment by jief666** [comment]
no, sorry. After having made this patch, I realized that the SSD wasn't working properly on macOS.
It worked at first and after one day, sectors were mixed up. Don't know why.
That's why I've stopped trying to make it work under recent macOs version.

**Comment by jief666** [comment]
Closed by mistake

**Comment by jamesst20** [comment]
> orry. After having made this patch, I realized that the SSD wasn't working properly on macOS.
> It worked at first and after one day, sectors were mixed up. Don't know why.
> That's why I've stopped trying to make it work under recent macOs version.

So even your current patch for 10.15.1 in this PR doesn't work very well?

Do you think it's possible to load the kext IONVMeFamily from 10.14.0 and use an older patch like this one ?

``` <dict>
    <key>Comment</key>
    <string>(10.14.0) IONVMeFamily: Ignore FLBAS bit:4 being set - for Plextor/LiteOn/Hynix</string>
    <key>Disabled</key>
    <false/>
    <key>Name</key>
    <string>IONVMeFamily</string>
    <key>Find</key>
    <data>ikga9sEQ</data>
    <key>Replace</key>
    <data>ikga9sEA</data>
  </dict>
```

[IONVMeFamily_10.14.kext.zip](https://github.com/RehabMan/patch-nvme/files/6061530/IONVMeFamily_10.14.kext.zip)

**Comment by jief666** [comment]
I'd say the patch works well : the SSD is seen. But there is another problem. More complicated one.

**Pull request closed without merging**
